-- ============================================================
--  Blog CMS — Supabase schema
--  Run this in the Supabase SQL editor for the portfolio project.
-- ============================================================

-- 1. Blog table -------------------------------------------------
create table if not exists public."Blog" (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  title        text not null,
  excerpt      text,
  content      text,                       -- rich-text HTML from the admin editor
  cover_image  text,                       -- public URL from the Blog_images bucket
  tags         text[] default '{}',
  status       text not null default 'draft'
               check (status in ('draft', 'published')),
  read_time    int  default 1,             -- estimated minutes to read
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  published_at timestamptz
);

-- keep updated_at fresh on every update
create or replace function public.set_blog_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_blog_updated_at on public."Blog";
create trigger trg_blog_updated_at
  before update on public."Blog"
  for each row execute function public.set_blog_updated_at();

-- helpful indexes
create index if not exists blog_status_idx        on public."Blog" (status);
create index if not exists blog_published_at_idx   on public."Blog" (published_at desc);

-- 2. Row Level Security ----------------------------------------
alter table public."Blog" enable row level security;

-- Public site: anyone may read PUBLISHED posts only
drop policy if exists "Public can read published blogs" on public."Blog";
create policy "Public can read published blogs"
  on public."Blog" for select
  using (status = 'published');

-- Admin (authenticated users) may do everything, incl. read drafts
drop policy if exists "Authenticated manage blogs" on public."Blog";
create policy "Authenticated manage blogs"
  on public."Blog" for all
  to authenticated
  using (true)
  with check (true);

-- 3. Storage bucket for cover images ---------------------------
insert into storage.buckets (id, name, public)
values ('Blog_images', 'Blog_images', true)
on conflict (id) do nothing;

-- Public read of blog images
drop policy if exists "Public read blog images" on storage.objects;
create policy "Public read blog images"
  on storage.objects for select
  using (bucket_id = 'Blog_images');

-- Authenticated users may upload / delete blog images
drop policy if exists "Authenticated write blog images" on storage.objects;
create policy "Authenticated write blog images"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'Blog_images')
  with check (bucket_id = 'Blog_images');
